=== kapes316/tlsprofiler/json/tlshandshake.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://firebird.cisco.com/tlshandshake.schema.json",
    "title": "TLS Profiler",
    "type": "object",
    "properties": {
        "versionID": {
            "type": "string"
        },
        "url": {
            "type": "string"
        },
        "connectionStatus": {
            "type": "number",
            "description": "0 if the tcp connection was ok, non-zero if not"
        },
        "negotiatedTLSVersion": {
            "type": "string"
        },
        "negotiatedCipher": {
            "type": "object",
            "properties": {
                "cipherName": {
                    "type": "string"
                },
                "cipherNumber": {
                    "type": "number"
                }
            },
            "required": [
                "cipherName",
                "cipherNumber"
            ]
        },
        "extensions": {
            "description": "TLS extensions sent back in the server hello",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "extensionName": {
                        "type": "string"
                    },
                    "extensionNumber": {
                        "type": "number"
                    }
                }
            },
            "uniqueItems": true
        },
        "serverCertificate": {
            "description": "PEM encoded certificate chain",
            "type": "array",
            "certificate": {
                "description": "one line of pem",
                "type": "string"
            }
        }
    },
    "required": [
        "url",
        "connectionStatus"
    ]
}

=== kapes316/tlsprofiler/json/tlshandshake.json
{
    "versionID": "openssl-1.1.1-myID",
    "url": "www.cisco.com",
    "connectionStatus": 0,
    "negotiatedTLSVersion": "1.2",
    "negotiatedCipher": { "cipherName": "super cipher", "cipherNumber": 3344 },
    "extensions": [{"extensionName": "Extended Master Secret","extensionNumber": 23}, {"extensionName": "Intended Master Secret","extensionNumber": 223}],
    "serverCertificate" : [
        "-----BEGIN CERTIFICATE-----",
        "MIICPjCCAcSgAwIBAgIJAI44Bto+Le4vMAoGCCqGSM49BAMCMF0xCzAJBgNVBAYT",
        "AkVDMQ4wDAYDVQQIDAVDdXJ2ZTERMA8GA1UEBwwIRWxsaXB0aWMxEjAQBgNVBAoM",
        "CXNlY3AzODRyMTEXMBUGA1UEAwwObGludXgyLmJjbS5wcnYwHhcNMTUxMDE5MTky",
        "MzA3WhcNMjUxMDE2MTkyMzA3WjBdMQswCQYDVQQGEwJFQzEOMAwGA1UECAwFQ3Vy",
        "dmUxETAPBgNVBAcMCEVsbGlwdGljMRIwEAYDVQQKDAlzZWNwMzg0cjExFzAVBgNV",
        "BAMMDmxpbnV4Mi5iY20ucHJ2MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE/OFDd2s8",
        "+H06XyFEgvRW9xdv/EN6OIPz5uAXT8Ng/Y0OzEgnULoJ3InYYPm5KP1gfobZuSYl",
        "IBuIG12NP3dVeSOFTq1YEbmR6IvYRJBN8PWCpC6CG0rGY7JnuKwxLPNpo1AwTjAd",
        "BgNVHQ4EFgQUoa6xH7JtjHGfcglaMuUjZIk0sTcwHwYDVR0jBBgwFoAUoa6xH7Jt",
        "jHGfcglaMuUjZIk0sTcwDAYDVR0TBAUwAwEB/zAKBggqhkjOPQQDAgNoADBlAjEA",
        "8GVYXC0Fh2yyZQXdigyRF1xgFUFHaz8XZeW/WJ6fK8ltNSA5Og5FLz4hN1y3NlVO",
        "AjBIIIRtlCmt1PTHZv2A/8W+v9wPSgwXC8yJnuTyTvjlzTokmvrVURVN17PRqn49",
        "Xzk=",
        "-----END CERTIFICATE-----"
    ]
}
